# Generated by Django 3.0.7 on 2020-07-17 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='dname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='prices',
            new_name='price',
        ),
    ]
