# Generated by Django 3.0.7 on 2020-08-16 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdate', models.DateField()),
                ('Movies Name', models.CharField(max_length=60)),
                ('hero', models.CharField(max_length=60)),
                ('heroine', models.CharField(max_length=60)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
