# Generated by Django 3.0.7 on 2020-08-17 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_auto_20200816_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Movies Name',
            new_name='movieName',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='Release Date',
            new_name='rdate',
        ),
    ]
