# Generated by Django 3.0.7 on 2020-08-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('emp_name', models.CharField(max_length=250)),
                ('emp_salary', models.FloatField()),
                ('emp_address', models.CharField(max_length=250)),
            ],
        ),
    ]
